# Generated by Django 4.0.4 on 2022-05-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/default.gif', height_field='300', upload_to='courses/%Y/%m/%d/', width_field='200'),
        ),
    ]
