# Generated by Django 4.0.4 on 2022-05-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/default.gif', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
